#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

while test $# -gt 0; do
  case "$1" in
    --debug)
      LOG_LEVEL=$DEBUG

      shift
      ;;
    --log-level*)
      level=`echo $1 | sed -e 's/^[^=]*=//g'`

      if [[ $level -ge $ERROR ]] && [[ $level -le $DEBUG ]]; then
        LOG_LEVEL=$level
      fi

      shift
      ;;
    --without*)
      name=`echo $1 | sed -e 's/^[^=]*=//g'`
      _excluded_installers+=("${name}_installer")

      shift
      ;;
    --only*)
      name=`echo $1 | sed -e 's/^[^=]*=//g'`

      require_installer $name
      log_success "complete."

      exit 0
      ;;
    *)
      break
      ;;
  esac
done

require_installer package-manager
require_installer emacs
require_installer zsh
require_installer node
require_installer devtools
require_installer go
require_installer fonts

log_success "complete."
