#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/installers/shared.sh"

while test $# -gt 0; do
  case "$1" in
    --debug)
      LOG_LEVEL=$DEBUG

      shift
      ;;
    --log-level*)
      LEVEL=`echo $1 | sed -e 's/^[^=]*=//g'`

      if [[ $LEVEL -ge $ERROR ]] && [[ $LEVEL -le $DEBUG ]]; then
        LOG_LEVEL=$LEVEL
      fi

      shift
      ;;
    *)
      break
      ;;
  esac
done

require_installer package-manager
require_installer emacs
require_installer zsh
require_installer node
require_installer devtools
require_installer go

log_success "complete."
