#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

packages=(
  ag
  cmake
  fzf
  fasd
  llvm
  "--HEAD cquery"
  "--HEAD ccls"
)

for package in "${packages[@]}"; do
  brew_install $package
done
