#!/usr/bin/env bash

require_installer package-manager

install_font() {
  local font=$1

  if [[ "$CHECKED_FOR_CASK_FONTS" != "t" ]]; then
    brew_tap homebrew/cask-fonts
    CHECKED_FOR_CASK_FONTS="t"
  fi

  brew_cask_install $font
}

install_font font-source-code-pro
install_font font-hack
