#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

install_go() {
  if ! command_exists go; then
    if [ ! -d ~/go ]; then
      mkdir ~/go
    fi

    if [ ! -d ~/go/src/github.com/user ]; then
      mkdir -p ~/go/src/github.com/user
    fi

    export GOPATH=$HOME/go
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=$PATH:$GOPATH/bin
    export PATH=$PATH:$GOROOT/bin

    brew_install go
  else
    log_found_package "go"
  fi
}

go_get() {
  local package=$1
  local name=$(basename $package)

  if ! command_exists "$name"; then
    log_install_package "$name"
    go get -u $package
  else
    log_found_package "$name"
  fi
}

install_go_packages() {
  if ! command_exists go; then
    install_go
  fi

  go_get "golang.org/x/tools/cmd/goimports"
  go_get "github.com/nsf/gocode"
  go_get "golang.org/x/tools/cmd/guru"
}

install_go
install_go_packages
