#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

install_go() {
  if ! command_exists go; then
    if [ ! -d ~/go ]; then
      mkdir ~/go
    fi

    if [ ! -d ~/go/src/github.com/user ]; then
      mkdir -p ~/go/src/github.com/user
    fi

    if is_macos; then
      export GOROOT=/usr/local/opt/go/libexec
    else
      export GOROOT=/usr/local/go
    fi

    export GOPATH=$HOME/go
    export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

    if is_macos; then
      brew_install go
    fi

    if is_linux; then
      GO_VERSION="1.12.2"

      log_install_package "go"

      apt_update
      wget https://dl.google.com/go/go$GO_VERSION.linux-amd64.tar.gz > /dev/null 2>&1
      sudo tar -xvf go$GO_VERSION.linux-amd64.tar.gz > /dev/null 2>&1
      sudo mv go /usr/local
      rm -rf go$GO_VERSION.linux-amd64.tar.gz

      sudo ln -s /usr/local/go/bin/* /usr/local/bin/
    fi
  else
    log_found_package "go"
  fi
}

go_get() {
  local package=$1
  local name=$(basename $package)

  if ! command_exists "$name"; then
    log_install_package "$name"
    go get -u $package
  else
    log_found_package "$name"
  fi
}

install_go_packages() {
  if ! command_exists go; then
    install_go
  fi

  go_get "golang.org/x/tools/cmd/goimports"
  go_get "github.com/nsf/gocode"
  go_get "golang.org/x/tools/cmd/guru"
}

install_go
install_go_packages
