#!/usr/bin/env bash

install_homebrew() {
  if ! which brew > /dev/null 2>&1; then
    log_info "installing homebrew..."

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  else
    log_info "found brew installation. skipping..."
  fi
}

install_homebrew
