#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

source_nvm() {
  export NVM_DIR="$HOME/.nvm"

  [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
}

install_nvm() {
  if [ ! -d ~/.nvm ]; then
    log_info "installing nvm..."

    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
    source_nvm
    nvm install stable
  else
    log_message "nvm already installed. skipping..."
  fi
}

install_nvm
source_nvm
brew_install yarn
