#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

install_homebrew() {
  if ! command_exists brew; then
    log_install_package "homebrew"

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  else
    log_found_package "homebrew"
  fi
}

install_aptitude() {
  apt_install aptitude
}

if is_macos; then
  install_homebrew
elif is_linux; then
  install_aptitude
else
  log_error "unknown system"
fi
