#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

install_homebrew() {
  if ! command_exists brew; then
    log_install_package "homebrew"

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
  else
    log_found_package "homebrew"
  fi
}

install_homebrew
