#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

require_installer package-manager

install_zlib() {
  brew_install readline xz
}

install_pyenv() {
  brew_install pyenv
}

install_python() {
  export LDFLAGS="-L/usr/local/opt/zlib/lib"
  export CPPFLAGS="-I/usr/local/opt/zlib/include"

  pyenv install 3.7.3 > /dev/null 2>&1
  pyenv install 2.7.16 > /dev/null 2>&1
}

install_zlib
install_pyenv
install_python
