#!/usr/bin/env bash

source "${BASH_SOURCE%/*}/shared.sh"

if is_linux; then
  # apt-get update
  apt_update
  # apt-get install zsh
  apt_install zsh

  if [ ! $(echo $SHELL) == $(which zsh) ]; then
    # set zsh as the default shell
    sudo usermod -s $(which zsh) $(whoami)
  fi
fi

# clone oh-my-zsh
git_clone git@github.com:robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

# symlink zsh files
symlink_dotfile zshrc ~/.zshrc
symlink_dotfile zsh ~/.zsh
symlink_dotfile zsh/zshenv ~/.zshenv

# source the .zshrc file
source ~/.zshrc
